[tool.poetry]
name = "booth_finder"
version = "0.1.0"
description = ""
authors = ["pistatium"]

[tool.poetry.dependencies]
python = "^3.8"
tweepy = "^4.5.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
